### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by JadedBlueEyes** [liyasthomas/banner#1]
**Describe the bug**
Editing the title text of the banner does not work on iOS safari.

**To Reproduce**
1. Go to the app on iOS safari
2. Click on the title
3. Attempt to edit the text
4. Nothing happens

**Expected behavior**
A cursor should be shown and the text should be editable.

**Screenshots**

**Tablet/Phone**
 - OS: iOS
 - Browser: safari
 - Version: 12.4 (Beta)
 - Device: iPad 6th generation

**Comment by liyasthomas** [comment]
Fixed

**Comment by JadedBlueEyes** [comment]
Still doesn’t seem to be working for me, even on my iOS 13 device - have you deployed it?

**Comment by liyasthomas** [comment]
@JoelEllis Ohh.  I see.. most prolly device specific bug, anyway lemme run some more tests and will let you know
